# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/alireza/Uni/Computer-Engineering/Labs/1/Debouncer/Debouncer.srcs/sources_1/new/PYNQ-Z1_C.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_encoder_0_0/design_1_encoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_encoder_0_0 || ORIG_REF_NAME==design_1_encoder_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_0_1/design_1_debouncer_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debouncer_0_1 || ORIG_REF_NAME==design_1_debouncer_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_1_0/design_1_debouncer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debouncer_1_0 || ORIG_REF_NAME==design_1_debouncer_1_0} -quiet] -quiet

# XDC: /home/alireza/Uni/Computer-Engineering/Labs/1/Debouncer/Debouncer.gen/sources_1/bd/design_1/design_1_ooc.xdc
