# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/TUD/Vivado_Projects/CE_Lab1/Road_Sign/PYNQ-Z1_C.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_road_sign_0_0/design_1_road_sign_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_road_sign_0_0 || ORIG_REF_NAME==design_1_road_sign_0_0} -quiet] -quiet

# XDC: e:/TUD/Vivado_Projects/CE_Lab1/Road_Sign/Road_Sign.gen/sources_1/bd/design_1/design_1_ooc.xdc
