set_property SRC_FILE_INFO {cfile:/home/alireza/Uni/Computer-Engineering/Labs/1/Debouncer/Debouncer.gen/sources_1/bd/design_1/ip/design_1_encoder_0_0/design_1_encoder_0_0/design_1_encoder_0_0_in_context.xdc rfile:../../../../../Debouncer.gen/sources_1/bd/design_1/ip/design_1_encoder_0_0/design_1_encoder_0_0/design_1_encoder_0_0_in_context.xdc id:1 order:EARLY scoped_inst:design_1_i/encoder_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alireza/Uni/Computer-Engineering/Labs/1/Debouncer/Debouncer.gen/sources_1/bd/design_1/ip/design_1_debouncer_0_1/design_1_debouncer_0_1/design_1_debouncer_0_1_in_context.xdc rfile:../../../../../Debouncer.gen/sources_1/bd/design_1/ip/design_1_debouncer_0_1/design_1_debouncer_0_1/design_1_debouncer_0_1_in_context.xdc id:2 order:EARLY scoped_inst:design_1_i/debouncer_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alireza/Uni/Computer-Engineering/Labs/1/Debouncer/Debouncer.gen/sources_1/bd/design_1/ip/design_1_debouncer_1_0/design_1_debouncer_1_0/design_1_debouncer_1_0_in_context.xdc rfile:../../../../../Debouncer.gen/sources_1/bd/design_1/ip/design_1_debouncer_1_0/design_1_debouncer_1_0/design_1_debouncer_1_0_in_context.xdc id:3 order:EARLY scoped_inst:design_1_i/debouncer_1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alireza/Uni/Computer-Engineering/Labs/1/Debouncer/Debouncer.srcs/sources_1/new/PYNQ-Z1_C.xdc rfile:../../../../../Debouncer.srcs/sources_1/new/PYNQ-Z1_C.xdc id:4} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alireza/Uni/Computer-Engineering/Labs/1/Debouncer/Debouncer.runs/synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:5} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells design_1_i/encoder_0]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells design_1_i/debouncer_0]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells design_1_i/debouncer_1]
set_property src_info {type:XDC file:4 line:9 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 -name sys_clk_pin -waveform {0.000 4.000} -add [get_ports sysclk]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells design_1_i]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells design_1_i/encoder_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells design_1_i/debouncer_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells design_1_i/debouncer_1]
